"""Email reporter — sends HTML digest with severity counts and findings table."""

from __future__ import annotations

import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from secaudit.config import AppConfig
from secaudit.models import TriageResult
from secaudit.reporters.base import BaseReporter

log = logging.getLogger(__name__)

SEVERITY_COLORS = {
    "CRITICAL": "#d32f2f",
    "HIGH": "#f57c00",
    "MEDIUM": "#fbc02d",
    "LOW": "#388e3c",
}


def _build_html(triage: TriageResult, notion_urls: dict | None = None, repo_name: str = "") -> str:
    """Generate HTML email body."""
    notion_urls = notion_urls or {}
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    repo_label = f" — {repo_name}" if repo_name else ""

    counts = {s: len(triage.findings.get(s, [])) for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW")}
    total = sum(counts.values())

    # Severity count boxes
    count_boxes = ""
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        color = SEVERITY_COLORS[sev]
        count_boxes += (
            f'<td style="text-align:center;padding:10px;background:{color};color:white;'
            f'border-radius:4px;margin:2px;"><strong>{counts[sev]}</strong><br>'
            f"<small>{sev}</small></td>"
        )

    # Findings table rows
    rows = ""
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        color = SEVERITY_COLORS[sev]
        for i, finding in enumerate(triage.findings.get(sev, [])):
            notion_link = ""
            sev_urls = notion_urls.get(sev, [])
            if i < len(sev_urls):
                notion_link = (
                    f' &nbsp;<a href="{sev_urls[i]}" '
                    f'style="font-size:11px;">View in Notion &rarr;</a>'
                )
            rows += f"""
            <tr>
              <td style="padding:8px;border-bottom:1px solid #eee;">
                <span style="background:{color};color:white;padding:2px 8px;border-radius:3px;
                font-size:11px;font-weight:bold;">{sev}</span>
              </td>
              <td style="padding:8px;border-bottom:1px solid #eee;">
                <strong>{finding.title}</strong>{notion_link}<br>
                <span style="color:#666;font-size:12px;">{finding.description[:200]}</span>
              </td>
              <td style="padding:8px;border-bottom:1px solid #eee;font-size:12px;color:#333;">
                {finding.recommendation}
              </td>
            </tr>"""

    findings_section = (
        '<p style="color:green;font-size:16px;">No findings to report.</p>'
        if total == 0
        else f"""
    <table style="width:100%;border-collapse:collapse;margin-top:16px;">
      <thead>
        <tr style="background:#f0f0f0;">
          <th style="padding:8px;text-align:left;width:90px;">Severity</th>
          <th style="padding:8px;text-align:left;">Finding</th>
          <th style="padding:8px;text-align:left;">Recommendation</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>"""
    )

    return f"""
<html><body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;">
  <h2 style="color:#1a1a2e;">Security Scan Digest — {today}{repo_label}</h2>
  <p style="background:#f5f5f5;padding:12px;border-left:4px solid #1a1a2e;">{triage.summary}</p>

  <table style="border-collapse:collapse;width:100%;margin:8px 0;">
    <tr>{count_boxes}</tr>
  </table>

  {findings_section}

  <p style="color:#999;font-size:11px;margin-top:24px;">
    Generated by secaudit &middot; {datetime.now(timezone.utc).isoformat()}Z
  </p>
</body></html>"""


class EmailReporter(BaseReporter):
    """Sends an HTML email digest with color-coded severity counts and findings table.

    Supports configurable send policies (all, findings_only, critical_only) and
    includes Notion page links when available. Connects via SMTP with STARTTLS.

    Kwargs:
        repo_name (str): Included in subject line for multi-repo scans.
        notion_urls (dict): Severity -> URL list for linking findings to Notion pages.
    """

    name = "email"

    def report(self, triage: TriageResult, config: AppConfig, **kwargs) -> dict:
        ec = config.email
        if not ec.enabled or not all([ec.username, ec.password, ec.to]):
            log.warning("Email not configured, skipping.")
            return {}

        # Check send_on policy
        has_findings = triage.total_findings > 0
        has_critical = triage.has_critical
        if ec.send_on == "findings_only" and not has_findings:
            log.info("No findings, skipping email (send_on=findings_only)")
            return {}
        if ec.send_on == "critical_only" and not has_critical:
            log.info("No critical findings, skipping email (send_on=critical_only)")
            return {}

        repo_name = kwargs.get("repo_name", "")
        notion_urls = kwargs.get("notion_urls", {})

        counts = {s: len(triage.findings.get(s, [])) for s in ("CRITICAL", "HIGH")}
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        repo_label = f" [{repo_name}]" if repo_name else ""

        if counts["CRITICAL"] or counts["HIGH"]:
            subject = f"Security Scan: {counts['CRITICAL']} Critical, {counts['HIGH']} High — {today}{repo_label}"
        else:
            subject = f"Security Scan Clean — {today}{repo_label}"

        html = _build_html(triage, notion_urls, repo_name)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = ec.from_addr
        msg["To"] = ", ".join(ec.to)
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(ec.smtp_host, ec.smtp_port) as server:
                server.starttls()
                server.login(ec.username, ec.password)
                server.sendmail(ec.from_addr, ec.to, msg.as_string())
            log.info("Email sent to %s", ", ".join(ec.to))
        except Exception as e:
            log.error("Failed to send email: %s", e)
            return {"error": str(e)}

        return {"sent_to": ec.to, "subject": subject}
