"""PR commenter — posts scan results as PR comments with collapsible sections."""

from __future__ import annotations

import logging

import requests

from secaudit.config import AppConfig
from secaudit.models import TriageResult
from secaudit.utils.retry import retry

log = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
MARKER = "<!-- secaudit-scan-results -->"

SEVERITY_EMOJI = {
    "CRITICAL": "\U0001f534",
    "HIGH": "\U0001f7e0",
    "MEDIUM": "\U0001f7e1",
    "LOW": "\U0001f7e2",
}


def _build_comment(triage: TriageResult) -> str:
    """Build a markdown PR comment with collapsible severity sections."""
    counts = {s: len(triage.findings.get(s, [])) for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW")}
    total = sum(counts.values())

    header = f"{MARKER}\n## Security Scan Results\n\n"
    header += f"**{triage.summary}**\n\n"

    # Summary badges
    badges = " | ".join(
        f"{SEVERITY_EMOJI.get(s, '')} **{counts[s]}** {s}"
        for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW")
    )
    header += f"{badges}\n\n"

    if total == 0:
        return header + "No security findings detected.\n"

    body = ""
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        findings = triage.findings.get(sev, [])
        if not findings:
            continue

        body += f"<details>\n<summary>{SEVERITY_EMOJI.get(sev, '')} {sev} ({len(findings)})</summary>\n\n"
        body += "| Finding | Recommendation |\n|---|---|\n"
        for f in findings:
            title = f.title.replace("|", "\\|")
            rec = f.recommendation.replace("|", "\\|")[:200]
            body += f"| **{title}**<br><sub>{f.scanner}</sub> | {rec} |\n"
        body += "\n</details>\n\n"

    footer = "\n---\n<sub>Generated by secaudit</sub>\n"

    return header + body + footer


class PRCommenter:
    """Posts and updates scan result comments on GitHub PRs."""

    def __init__(self, config: AppConfig):
        self.token = config.github.token
        self._session = requests.Session()
        if self.token:
            self._session.headers["Authorization"] = f"Bearer {self.token}"
        self._session.headers["Accept"] = "application/vnd.github+json"

    @retry(max_attempts=3, base_delay=1.0, exceptions=(requests.RequestException,))
    def post_or_update(self, owner: str, repo: str, pr_number: int, triage: TriageResult) -> str | None:
        """Post a new comment or update an existing one.

        Returns the comment URL on success.
        """
        comment_body = _build_comment(triage)

        # Check for existing comment to update
        existing_id = self._find_existing_comment(owner, repo, pr_number)
        if existing_id:
            return self._update_comment(owner, repo, existing_id, comment_body)
        return self._create_comment(owner, repo, pr_number, comment_body)

    def _find_existing_comment(self, owner: str, repo: str, pr_number: int) -> int | None:
        """Find our existing comment by marker text."""
        resp = self._session.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
            params={"per_page": 100},
            timeout=15,
        )
        if resp.status_code != 200:
            return None
        for comment in resp.json():
            if MARKER in comment.get("body", ""):
                return comment["id"]
        return None

    def _create_comment(self, owner: str, repo: str, pr_number: int, body: str) -> str | None:
        resp = self._session.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
            json={"body": body},
            timeout=15,
        )
        if resp.status_code == 201:
            url = resp.json().get("html_url")
            log.info("Posted PR comment: %s", url)
            return url
        log.warning("Failed to post PR comment: %d", resp.status_code)
        return None

    def _update_comment(self, owner: str, repo: str, comment_id: int, body: str) -> str | None:
        resp = self._session.patch(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues/comments/{comment_id}",
            json={"body": body},
            timeout=15,
        )
        if resp.status_code == 200:
            url = resp.json().get("html_url")
            log.info("Updated PR comment: %s", url)
            return url
        log.warning("Failed to update PR comment: %d", resp.status_code)
        return None
